### ISSUE TITLE
Stundenplan POST

### ISSUE THREAD

**Issue by FauxKiwi** [ChaosSchulInformatiker/Software-Projekt#4]
POST maristenapi.tk/edit/49867e3823dad67/
`49867e3823dad67 is id for "edit schedules"`

format(json):

day: [0-4]
hour: [1-14]
Lesson:
subject: String ("D" | "E" | "INF" | ...)
teacher: String ("POHL" | "SCHN" | ...)
room: Optional String ("Ph4" | "5A" | "Mu2" | "8RB" | ...)

**Comment by LOENS2** [comment]
unused!
